package buttons;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import situations.*;

/**
 * @author Leo Man, Jacky Phuong
 * 
 * */

/**
 * Represents an abstract button in a calculator
 */
public abstract class CalculatorButton extends JButton implements ActionListener {

	/** The Current situation of the calculator */
	Situation situation;

	/**
	 * Constructs a CalculatorButton with the specified label and situation.
	 * 
	 * @param label     The label displayed on the button
	 * 
	 * @param situation The current situation of the calculator
	 */
	public CalculatorButton(String label, Situation situation) {
		super(label);
		this.situation = situation;

		this.setPreferredSize(new Dimension(100, 100));
		this.setBackground(Color.WHITE);

		this.setFont(new Font("Arial", Font.PLAIN, 40));
		this.addActionListener(this);
	}

	/**
	 * Performs the appropriate transition when this button is clicked
	 */
	public abstract void transition();

	/**
	 * Sets the background color of the button
	 * 
	 * @param color The color set
	 */
	public void setColor(Color color) {
		this.setBackground(color);
	}

	/**
	 * Sets the border color of the button
	 * 
	 * @param color The color of the border to set
	 */
	public void setBorder(Color color) {
		setBorder(BorderFactory.createLineBorder(color));
	}

	/**
	 * Retrieves the string representation of the button label
	 * 
	 * @return The button label
	 */
	@Override
	public String toString() {
		return this.getText();
	}

	/**
	 * Performs an action when the button is clicked, triggering the transition
	 * 
	 * @param e The ActionEvent generated by the button click
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		transition();
	}
}
